### ISSUE TITLE
Card-tracker support

### ISSUE THREAD

**Issue by johntdyer** [renemarc/home-assistant-doomsday-clock#1]
Any thoughts on setting this up so it’s supported by custom updater  ?

https://github.com/custom-components/custom_updater

**Comment by renemarc** [comment]
Good idea! I'll add it to my task list, thanks! 😃

**Comment by renemarc** [comment]
[Release 2.0.1](https://github.com/renemarc/home-assistant-doomsday-clock/releases/tag/2.0.1) now features support for Custom Updater.

**Comment by renemarc** [comment]
@all-contributors add @johntdyer for idea

**Comment by renemarc** [comment]
@all-contributors please add @johntdyer for idea
