### ISSUE TITLE
Integration doomsday_clock not found when trying to verify its sensor platform.

### ISSUE THREAD

**Issue by JamieP83** [renemarc/home-assistant-doomsday-clock#2]
hey,
followed your instructions, but get this error: 

> Integration doomsday_clock not found when trying to verify its sensor platform.

Senror:
  - platform: doomsday_clock
    scan_interval: 86400

file location: \\HASSIO\config\custom_components\sensor

i have rebooted Hassio
i have double checked all spelling and that the py is correct (taken from raw)

**Comment by renemarc** [comment]
Hi @jamiepryer,

Home Assistant [has indeed recently changed its file structure](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html) for components. This custom component should instead be renamed from `doomsday_clock.py` to `sensor.py` and placed into its own folder: `\HASSIO\config\custom_components\doomsday_clock\`

Thanks for the heads up, I'll update the repo to match this new structure!

**Comment by JamieP83** [comment]
thanks a lot!! :)

**Comment by JamieP83** [comment]
didnt work im afraid.
anything else to change sorry?

**Comment by renemarc** [comment]
That's strange. What's your Home Assistant version? Any related errors showing if you set the [logger component](https://www.home-assistant.io/components/logger/) to debug level?

For reference, my HA configuration is set this way [on its develop branch](https://github.com/renemarc/home-assistant-config/tree/develop):

```shell
/custom_components/doomsday_clock/sensor.py
```

The component [is configured](https://github.com/renemarc/home-assistant-config/blob/develop/sensors/atmosphere.yaml) with:

```yaml
sensor:
  - platform: doomsday_clock
    scan_interval: 86400
```

Then [using Lovelace](https://github.com/renemarc/home-assistant-config/blob/develop/ui-lovelace.yaml), the card is displayed on the frontend:

```yaml
views:
  - title: Weather
    cards:
      - type: entities
        entities:
          - sensor.doomsday_clock
```

**Comment by JamieP83** [comment]
Hey,
so i have this:
Raspberry PI, V0.93.2


> arch | armv7l
> -- | --
> dev | false
> docker | true
> hassio | true
> os_name | Linux
> python_version | 3.7.3
> timezone | Europe/London
> version | 0.93.2
> virtualenv | false
> 
> 

\\HASSIO\config\custom_components\doomsday_clock

same file as from your pull.

then when i add to my config yaml, i get this error when i do a "check config"
`Platform not found: sensor.doomsday_clock`

Logs
```
019-06-03 07:51:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for doomsday_clock which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-03 07:51:26 INFO (MainThread) [homeassistant.loader] Loaded doomsday_clock from custom_components.doomsday_clock
```

**Comment by renemarc** [comment]
Thanks for the details! My Home Assistant version was a bit older than yours, and recent versions actually [required further file changes](https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html). Starting with [release 2.0.1](https://github.com/renemarc/home-assistant-doomsday-clock/tree/2.0.1) this component should now work properly on Home Assistant 0.91+.

Do let me know if this latest iteration works well on your end!

**Comment by JamieP83** [comment]
awesome!! thanks a lot, thats done it :)

**Comment by renemarc** [comment]
Yay, glad that we got this working again! 😃

**Comment by renemarc** [comment]
@all-contributors add @jamiepryer for bug

**Comment by renemarc** [comment]
@all-contributors add @jamiepryer for bug

**Comment by renemarc** [comment]
@all-contributors please add @jamiepryer for bug
